# Generated by Django 5.1.2 on 2024-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'timestamp'], name='location_de_device__8a3b91_idx')],
            },
        ),
    ]
